
version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: hypetur_mysql
    ports:
      - '8081:3306'
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: wp
  wordpress:
    image: wordpress:php5.6
    container_name: hypetur_wordpress
    volumes:
      - ./plugins/:/var/www/html/wp-content/plugins # Plugin development
      - ./hype-tur/:/var/www/html/wp-content/themes/hype-tur # Theme development
    ports:
      - '127.0.0.1:8080:80'
    links:
      - mysql:mysql
    environment:
      WORDPRESS_DB_PASSWORD: wp
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql:mysql
      depends_on:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: wp
      ports:
        - '8082:80'